### ISSUE TITLE
Run with 1366x768

### ISSUE THREAD

**Issue by caiobps1** [nebelorz/NST-medivia-bot#5]
How can i use this app in resolution 1366x768?

**Comment by nebelorz** [comment]
Hi there! You can use your own images, just replace the ones on the images folder for the ones you made (use the same names). 
I must tell you that this program is not maintaned, so maybe it's not working properly as Medivia got updated several times.

**Comment by nebelorz** [comment]
I'll let it open in case you've any doubts!
